### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Bakudankun** [Bakudankun/qline.vim#2]
- [x] Move `import/*` to `private/*` not to be imported from other plugins?
- [ ] How can I implement `%<` (truncation) component?
- [ ] Per-tier separator
- [x] Vim9 may not support `:import`-ing dynamic paths. Consider another method for colorscheme API
- [ ] Provide config presets that can be imported by `g:qline_config.using` list
- [ ] tabline
- [ ] Remove mode-specific config in favor of `g:qline_config.override` list to override config in any conditions
